#!/bin/sh

exec 2>&1

ZPRD_CONF='/etc/zprd.conf'

if ! [ -f "$ZPRD_CONF" ]; then
  echo "STARTUP ERROR: config file $ZPRD_CONF is missing"
  exit 1
fi

IFACE="$(grep '^I' "$ZPRD_CONF" | tail -1 | cut -c2-)"

if [ -z "$IFACE" ]; then
  echo "STARTUP ERROR: 'I' config statement is missing in $ZPRD_CONF"
  exit 1
fi

RUN_AS_USER="$(grep '^U' "$ZPRD_CONF" | tail -1 | cut -c2-)"

if [ -z "$(ip tuntap show | grep "^$IFACE:")" ]; then
  echo "STARTUP: setup tun device $IFACE"
  XTTA=''
  [ -n "$RUN_AS_USER" ] && XTTA="user $RUN_AS_USER"
  ip tuntap add mode tun $XTTA "$IFACE" || exit 1
  unset XTTA
fi

exec /usr/bin/zprd "C$ZPRD_CONF"
